# 2023-06-18 13:30
name: Test - on download

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'sha1 / sha256 / sha512'
        required: true
        default: 'sha256'
        type: choice
        options:
          - sha1
          - sha256
          - sha512
      ignore_git:
        description: 'Ignore ./.git/ .git/'
        type: boolean
        required: false
        default: true
      debug:
        description: 'Debug mode'
        required: false
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

env:
  TAG_NAME: "sha-checksums"
  VERSION: v1.0

jobs:
  Test:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: macos-11       }
          - { os: macos-12       }
          - { os: macos-13       }
          - { os: macos-latest   }
          - { os: ubuntu-20.04   }
          - { os: ubuntu-22.04   }
          - { os: ubuntu-latest  }
          - { os: windows-2019   }
          - { os: windows-2022   }
          - { os: windows-latest }

    steps:

      - name: Download putty and print sha256 from sha256sums
        shell: bash
        run: |
          if [ "${{ inputs.debug }}" == "yes" ]; then
            set -x;
          fi
          echo "download putty, windows 64bit, latest version. maybe is 0.78 ?!"
          curl -L -o putty-w64.zip https://the.earth.li/~sgtatham/putty/latest/w64/putty.zip;
          echo "download putty, sha256sums for latest version"
          curl -L -o putty-sha256sums https://the.earth.li/~sgtatham/putty/latest/sha256sums;
          putty_w64_checksum=$(grep "w64/putty.zip" putty-sha256sums | awk '{print $1}');
          echo "putty_w64_checksum=$putty_w64_checksum";
          if [ "$putty_w64_checksum" == "5288add504f818e3d505634a5ece1e35d4af3771fad095b35064d39ca4913130" ]; then
            echo "OK SHA256 = $putty_w64_checksum";
            echo "putty, windows 64bit, version 0.78, download OK"
            echo "putty_w64_checksum=$putty_w64_checksum" >> $GITHUB_ENV;
          fi

      - name: putty-w64.zip
        uses: deep-soft/sha-checksums@main
        with:
          type: ${{ github.event.inputs.type }}
          filename: '${{ env.TAG_NAME }}-${{ env.VERSION }}-${{ matrix.job.os }}.${{ github.event.inputs.type }}'
          directory: '.'
          path: 'putty-w64.zip'
          exclusions: ''
          debug: ${{ github.event.inputs.debug }}
          ignore_git: true
          # checksums filename is ${{ env.SHA_SUMS }}

      - name: test sha256
        shell: bash
        run: |
          putty_w64_checksum_v2=$(grep "putty-w64.zip" ${{ env.SHA_SUMS }} | awk '{print $1}');
          if [ $putty_w64_checksum_v2 == ${{ env.putty_w64_checksum }} ]; then
            echo "OK SHA256: $putty_w64_checksum_v2 == ${{ env.putty_w64_checksum }}";
            echo "putty_w64_checksum_v2=$putty_w64_checksum_v2" >> $GITHUB_ENV;
          fi

      - name: print env values
        shell: bash
        run: |
          echo "print env values: putty_w64_checksum and putty_w64_checksum_v2";
          echo "putty_w64_checksum    = ${{ env.putty_w64_checksum }}";
          echo "putty_w64_checksum_v2 = ${{ env.putty_w64_checksum_v2 }}";
          
      - name: Upload artifact
        continue-on-error: true
        uses: deep-soft/upload-artifact@main
        with:
          name: ${{ env.TAG_NAME }}-${{ env.VERSION }}-${{ matrix.job.os }}
          path: ${{ env.SHA_SUMS }}

      - name: Publish Release
        #continue-on-error: true
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          #tag_name: ${{ env.TAG_NAME }}-${{ env.VERSION }}-${{ matrix.job.os }}
          tag_name: ${{ env.TAG_NAME }}-${{ env.VERSION }}
          files: |
            ${{ env.SHA_SUMS }}
